name: SSH via Cloudflared

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup SSH via Cloudflared
      run: |
        chmod +x cloudflared2actions.sh
        ./cloudflared2actions.sh
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        
    - name: Continue workflow
      run: echo "工作流继续执行..."
