name: ubuntu
on:
  watch:
    types: started
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Start SSH via cloudflared
      uses: askme888/ssh2actions@main
      with:
        mode: cloudflared
      env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
